modality: ???
date_format: '%Y.%m.%d.%H.%M.%S'
experiment_uid: ${now:${date_format}}
output_dir: ${oc.env:WORLDBENCH_EXP_ROOT}/${modality}/${method_name}/${experiment_uid} # path where output csv is saved